### PR TITLE
loop plugin API changes

### PR DESCRIPTION
**Pull request by vojtechtrefny**
New argument for `bd_loop_setup` and a new function to get information about loop devices. UDisks needs to be adjusted to the new API before merging this.

Fixes: #685

### CODE REVIEW

**Review by tbzatek — APPROVED** [review]
Looks good

**Comment by vojtechtrefny** [comment]
Moved removing of bd_loop_get_backing_file to a separate PR #822 so this could be merged without breaking blivet.

**Review by tbzatek — APPROVED** [review]
Ok then.

**Comment by vojtechtrefny** [comment]
Last change, I promise :) Because we need the removed function only for Blivet and Anaconda, I decided to put a little "helper" one in the overrides which uses the new `bd_loop_info` function to get the backing file. This way removing it later will be just a small change in the python overrides.

**Comment by tbzatek** [comment]
> Last change, I promise :) Because we need the removed function only for Blivet and Anaconda, I decided to put a little "helper" one in the overrides which uses the new `bd_loop_info` function to get the backing file. This way removing it later will be just a small change in the python overrides.

Oh, interesting approach. I like it. Therefore: ship it!

**Pull request merged**
