### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by mbiebl**
Spotted by lintian

### CODE REVIEW

**Comment by mbiebl** [comment]
Should probably be pulled into master as well.

**Comment by blivetghoul** [comment]
Can one of the admins verify this patch?

**Review by vojtechtrefny — APPROVED** [review]
Thank you.

**Comment by vojtechtrefny** [comment]
Jenkins, ok to test.

**Review by tbzatek — APPROVED** [review]
Nice!

**Pull request merged**
