### PR TITLE
Move UNUSED definition to common header utils.h

### PR DESCRIPTION
**Pull request by giuliobenetti**
Let's move UNUSED defition to avoid redundancy.

### CODE REVIEW

**Comment by StorageGhoul** [comment]
Can one of the admins verify this patch?

**Review by vojtechtrefny — COMMENTED** [review]
I understand the simplification, but I am not a huge fan of adding a unprefixed and internal definition to a public header file. Thoughts @tbzatek?

**Comment by vojtechtrefny** [comment]
Jenkins, ok to test.

**Comment by giuliobenetti** [comment]
> This should all be changed to `G_GNUC_UNUSED` instead.

This is only defined for Glibc AFAIK, so for uclibc and musl we need to define it if not defined.
At this point we still need an internal header where redefine it if not defined.
If you point me the right internal header I can do that and include header where current UNUSED is used.

**Comment by tbzatek** [comment]
> This is only defined for Glibc AFAIK, so for uclibc and musl we need to define it if not defined.

It's a compiler attribute, it should be libc-implementation independent. Besides, if there's a problem with the macro, it should be reported and fixed on glib side. We use glib quite extensively in libblockdev. Another aspect is that this annotation is not used in public headers, only in the actual code.

**Comment by giuliobenetti** [comment]
> > This is only defined for Glibc AFAIK, so for uclibc and musl we need to define it if not defined.
> 
> It's a compiler attribute, it should be libc-implementation independent. Besides, if there's a problem with the macro, it should be reported and fixed on glib side. We use glib quite extensively in libblockdev. Another aspect is that this annotation is not used in public headers, only in the actual code.

AFAICS it is a glibc macro found in "#include <glib.h>"
https://developer-old.gnome.org/glib/stable/glib-Miscellaneous-Macros.html#G-GNUC-UNUSED:CAPS

So it's not suitable for other libc I deal in Buildroot for libblockdev. I can add a patch local to Buildroot but we prefer to upstream everything possibly. So it would be great if we find a way to have this upstreamed.
If you point me a private header where to place the definition like:
#define LIBBLOCKDEV_UNUSED __attribute__((unused))
I modify the patch.

**Comment by giuliobenetti** [comment]
> > > This is only defined for Glibc AFAIK, so for uclibc and musl we need to define it if not defined.
> > 
> > 
> > It's a compiler attribute, it should be libc-implementation independent. Besides, if there's a problem with the macro, it should be reported and fixed on glib side. We use glib quite extensively in libblockdev. Another aspect is that this annotation is not used in public headers, only in the actual code.
> 
> AFAICS it is a glibc macro found in "#include <glib.h>" https://developer-old.gnome.org/glib/stable/glib-Miscellaneous-Macros.html#G-GNUC-UNUSED:CAPS
> 
> So it's not suitable for other libc I deal in Buildroot for libblockdev. I can add a patch local to Buildroot but we prefer to upstream everything possibly. So it would be great if we find a way to have this upstreamed. If you point me a private header where to place the definition like:
> 
> ```
> #define LIBBLOCKDEV_UNUSED __attribute__((unused))
> ```
> 
> I modify the patch.

Pardon, I've mixed up glib and glibc. I'm testing right now. @tbzatek you're right, sorry for the noise!
Once checked I come up with a patch using G_GNUC_UNUSED instead of UNUSED.

**Comment by giuliobenetti** [comment]
> G_GNUC_UNUSED

I'm producing the patch right now and then I launch Buildroot autobuilder with all possible combinations, 72 arch/gcc/libc combinations. Once I have a working patch I push force so also your CI can test it :-)

**Comment by giuliobenetti** [comment]
Ok, updated the patch and launched Buildroot autobuilder(45 cases, not 74) and your CI is working, let's see the result.
I've successfully built for Arm+glibc at the moment.

**Comment by giuliobenetti** [comment]
Oops, I've dropped some UNUSED. Going to fix now

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me now, thank you.

**Comment by vojtechtrefny** [comment]
You can ignore the Debian testing CI failures, looks like pylint/astroid is broken after latest update, it's not related to this change.

**Comment by giuliobenetti** [comment]
> You can ignore the Debian testing CI failures, looks like pylint/astroid is broken after latest update, it's not related to this change.

Perfect. Indeed I was about to ask you to relaunch it because of cached sources resulting in build failure.
But we're fine now then. Also Buildroot autobuilder is running successfully now.

**Review by tbzatek — APPROVED** [review]
Looks good, thanks!

**Comment by giuliobenetti** [comment]
> Looks good, thanks!

Happy to contribute!

**Pull request merged**
