### PR TITLE
VDO plugin

### PR DESCRIPTION
**Pull request by vojtechtrefny**
New plugin for configuration of VDO devices.

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by tbzatek** [comment]
[0001-vdo-Resolve-real-device-file-path.patch.gz](https://github.com/storaged-project/libblockdev/files/2008708/0001-vdo-Resolve-real-device-file-path.patch.gz)

Small fix to handle various `/dev/disk/by-*`paths returned by the vdo commandline tool. Apparently this came with the `vdo-6.2.0.35-3.py3` update.

**Comment by tbzatek** [comment]
I would personally remove the WIP status as the current API tightly copies the `vdo` commandline tool options. However it turned out the `vdo` command output varies slightly across versions and python3 rewrite is currently in progress. 

@vojtechtrefny: your call, I think this is ready to merge.

I'm now going to have a look at adding `vdo` support to `udisks` though I don't expect any issues with regards to the `libblockdev` plugin API.

**Comment by tbzatek** [comment]
TODO: write tests for `bd_vdo_grow_physical()`

**Pull request merged**
