### PR TITLE
Remove __init__.py from out gi.overrides directory

### PR DESCRIPTION
**Pull request by vojtechtrefny**
When trying to run the code from the source if the `__init__.py`
exists in this directory GI importer tries to use it to import
internal GI functions instead of using the system location in
/usr/lib/python3.X/site-packages/gi.

```
In [1]: from gi.repository import BlockDev
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-7fcbc290705d> in <module>
----> 1 from gi.repository import BlockDev

/usr/lib/python3.10/site-packages/gi/repository/__init__.py in <module>
     21 import sys
     22 
---> 23 from ..importer import DynamicImporter
     24 
     25 sys.meta_path.append(DynamicImporter('gi.repository'))

/usr/lib64/python3.10/site-packages/gi/importer.py in <module>
     31 from ._gi import PyGIWarning
     32 from .module import get_introspection_module
---> 33 from .overrides import load_overrides
     34 
     35 

ImportError: cannot import name 'load_overrides' from 'gi.overrides' (/home/vtrefny/Projekty/libblockdev/src/python/gi/overrides/__init__.py)
```

### CODE REVIEW

**Review by tbzatek — APPROVED** [review]
I have absolutely no idea what you're talking about but removing files is always good!

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
> This used to work and was added to make things work. What has changed?

I have no idea. There were some changes in the python3-gobject-base package in Fedora 34 and some parts of the `gi` module are now in the `/usr/lib` folder instead of `/usr/lib64` so I guess python now prefers the local directory instead of the system one when trying the relative import.

**Pull request merged**
