### PR TITLE
Always use "--fs ignore" with lvresize

### PR DESCRIPTION
**Pull request by mvollmer**
Depending on how lvresize is compiled, it might default to "--fs checksize", which is not what we want for this low level API.

Also, "--fs checksize" does not always succeed even when the filesystem is the right size, such as when libblkid does not work for NTFS.

### CODE REVIEW

**Comment by StorageGhoul** [comment]
Can one of the admins verify this patch?

**Comment by mvollmer** [comment]
The interaction of inactive logical volumes, "--force", and "--fs" is
interesting: With "--fs checksize" and without "--force", a
inactive volume leads to an immediate error.  With "--force", the volume is temporarily activated, the checksize is performed and then the volume is deactivated again.

(When the check fails, or crashes, the volume is left activated. Not sure if that counts as a bug.)

Thus, the bd_lvm_resize would only succeed when the filesystem is already the right size for the new size of the logical volume. Is that would you see?

Anyway, this PR should help Cockpit avoid this situation: https://github.com/lvmteam/lvm2/issues/123

**Comment by mvollmer** [comment]
(I think `--force` should imply `--fs ignore`, but *shrug*.)

**Comment by tbzatek** [comment]
> With "--force", the volume is temporarily activated, the checksize is performed and then the volume is deactivated again.

Does this result in uevents being registered by UDisks, potentially accessing the block devices and blocking deactivation for a brief period of time?

**Review by tbzatek — APPROVED** [review]
I'm generally okay with this but I leave it up to @vojtechtrefny for his final decision.

**Review by vojtechtrefny — APPROVED** [review]
Thank you. Looks good to me. I hope this is the last fix for this new `lvresize --fs` nonsense...

**Pull request merged**
