### PR TITLE
fs/xfs: Use xfs_spaceman instead of xfs_db for mounted filesystems

### LINKED ISSUE #880: xfs_db might return outdated info for a mounted filesystem...
I made you switch to use xfs_db instead of xfs_info in #871, but turns out that xfs_db might return the old size when you run it right after growing a mounted xfs filesystem. xfs_info (via xfs_spaceman) return the new size.

Grrr.

### PR DESCRIPTION
**Pull request by mvollmer**
Fixes #880

### CODE REVIEW

**Comment by StorageGhoul** [comment]
Can one of the admins verify this patch?

**Comment by tbzatek** [comment]
Jenkins, ok to test.

**Review by tbzatek — APPROVED** [review]
yay!

**Review by vojtechtrefny — APPROVED** [review]

**Comment by mvollmer** [comment]
Here is the failed test: https://cockpit-logs.us-east-1.linodeobjects.com/pull-18616-20230503-120308-89480e9b-fedora-testing-dnf-copr/log.html#218

**Comment by mvollmer** [comment]
Can I help to get this in? :-)

**Pull request merged**
